services:
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.62.0
    ports:
      - '16686:16686'
    healthcheck:
      test: ["CMD-SHELL", "wget --spider http://localhost:16686/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  golang-job-scraper:
    container_name: golang-job-scraper
    build: .
    environment:
      - ENV=dev
      - NAME=golang-job-scraper
      - VERSION=0.1.0-alpha.0
      - LOGS_ADDRESS=
      - LOGS_API_KEY_VALUE=
      - TRACES_ADDRESS=jaeger:4318
      - TRACES_API_KEY_VALUE=
      - READ_WRITER_LOCATION=
      - SHEETS_SERVICE_ACCOUNT_KEY_PATH=/app/service_account_key.json
    volumes:
      - ./service_account_key.json:/app/service_account_key.json:ro
    depends_on:
      jaeger:
        condition: service_healthy
